export enum EstadoSolicitudArco {
  RECIBIDA = 'RECIBIDA',
  EN_REVISION = 'EN_REVISION',
  ATENDIDA = 'ATENDIDA',
  IMPROCEDENTE = 'IMPROCEDENTE',
  CUMPLIDA_AUTOMATICAMENTE = 'CUMPLIDA_AUTOMATICAMENTE',
  PENDIENTE_POR_OBLIGACIONES = 'PENDIENTE_POR_OBLIGACIONES',
}
