name: First Push
on:
  push:

jobs:
  Tarea1:
    runs-on: ubuntu-latest

    steps:
      - name: Say Ayy
        run: |
          echo "Hi my first Push"
          echo "My name is Gael Quintana Romero"
          echo "id ${{github.event.head_commit.message}}"
